apiVersion: v1
kind: Secret
metadata:
  name: app-portal-github-key
  namespace: app-portal
  labels:
    app.kubernetes.io/name: app-portal
    app.kubernetes.io/component: backend
type: Opaque
data:
  # GitHub App private key (base64 encoded)
  github-app-key.pem: ${AUTH_GITHUB_APP_PRIVATE_KEY_B64}