# Example local configuration for Kubernetes and TeraSky Ingestor
# Copy this file to app-config.local.yaml and update with your values

# Kubernetes cluster configuration
kubernetes:
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://127.0.0.1:6443  # Your Kubernetes API server URL
          name: rancher-desktop         # Or your cluster name (minikube, kind, etc.)
          authProvider: 'serviceAccount'
          skipTLSVerify: true           # For local development only
          serviceAccountToken: ${KUBERNETES_TOKEN}  # See setup instructions below

# To get a service account token:
# 1. Run the setup script to create the service account:
#    ./scripts/setup-cluster.sh
#
# 2. Get the token (the script will output it):
#    kubectl create token backstage-k8s-sa --duration=365d
#
# 3. Replace ${KUBERNETES_TOKEN} above with the actual token
#
# For production, use environment variables or a secrets manager

# Optional: Configure specific namespaces or resources to exclude
# kubernetesIngestor:
#   components:
#     excludedNamespaces:
#       - kube-system
#       - kube-public
#       - your-namespace-to-exclude