apiVersion: openportal.dev/v1alpha1
kind: DNSRecord
metadata:
  name: test-dns-record
  namespace: default
  labels:
    app: test-app
    backstage.io/catalog-entity: "component"
spec:
  type: A
  name: test
  value: "192.168.1.100"