---
# Fixed entities with correct annotations for TeraSky Crossplane plugin
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service-crossplane-v1
  title: Payment Service (Crossplane v1 Claims)
  description: Example service with Crossplane Claims pattern
  annotations:
    # Crossplane v1 annotations (Claims) - the plugin expects this format
    crossplane.io/claim-name: payment-database
    crossplane.io/claim-namespace: team-backend
    
    # TeraSky specific annotations the plugin needs
    terasky.backstage.io/claim-name: payment-database
    terasky.backstage.io/claim-namespace: team-backend
    terasky.backstage.io/claim-plural: postgresqlinstances
    terasky.backstage.io/claim-group: database.example.com
    terasky.backstage.io/claim-version: v1alpha1
    
    # Kubernetes ID with namespace/name format (important!)
    backstage.io/kubernetes-id: team-backend/payment-service
    backstage.io/kubernetes-namespace: team-backend
    backstage.io/kubernetes-label-selector: "app=payment-service,crossplane.io/claim-namespace=team-backend"
    backstage.io/kubernetes-cluster: rancher-desktop
    backstage.io/managed-by-location: "cluster: rancher-desktop"
spec:
  type: service
  lifecycle: production
  owner: team-backend
  system: payment-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service-crossplane-v2
  title: Inventory Service (Crossplane v2 XRs)
  description: Service with Crossplane v2 XRs
  annotations:
    # Try v2 pattern with namespace/name format
    crossplane.io/xr-name: inventory-mongodb-abc
    crossplane.io/xr-namespace: team-inventory
    
    # Kubernetes ID with namespace/name format
    backstage.io/kubernetes-id: team-inventory/inventory-service
    backstage.io/kubernetes-namespace: team-inventory
    backstage.io/kubernetes-label-selector: "app=inventory-service"
    backstage.io/kubernetes-cluster: rancher-desktop
    backstage.io/managed-by-location: "cluster: rancher-desktop"
spec:
  type: service
  lifecycle: production
  owner: team-inventory
  system: inventory-management
---
# Minimal test entity to see if basic integration works
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service-minimal
  title: Test Service (Minimal Annotations)
  description: Minimal test for Crossplane integration
  annotations:
    # Just the minimum required
    backstage.io/kubernetes-id: default/test-service
    backstage.io/kubernetes-namespace: default
    crossplane.io/claim-namespace: default
    backstage.io/kubernetes-cluster: rancher-desktop
    backstage.io/managed-by-location: "cluster: rancher-desktop"
spec:
  type: service
  lifecycle: experimental
  owner: team-platform